name: CI/CD for Flask App on Render

on:
  push:
    branches:
      - sw_dev_system
  pull_request:
    branches:
      - sw_dev_system

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
